name:      间歇性折腾
pygments:  true
mardown:   redcarpet
source:    .
destination: ./_site
layouts:   ./_layouts
permalink: /:year-:month-:day/:title.html 
baseurl:   /
paginate:  5
paginate_path: "page:num"

