name:      间歇性折腾
pygments:  true
source:    .
destination: ./_site
plugins:   ./_plugins
layouts:   ./_layouts
keep_files: ['.git','.svn']
permalink: /:year-:month-:day/:title.html 
baseurl:   /
paginate:  5
paginate_path: "page:num"
