permalink:     /:year-:month-:day/:title
url:           http://127.0.0.1:4000
author:        Geek_Pig
paginate:      15
markdown:      redcarpet
pygments:      true
safe:          true
auto:          true
