permalink:     /:year-:month-:day/:title.html
url:           http://uternet.github.io
author:        Geek_Gig
paginate:      6
markdown:      redcarpet
pygments:      true
safe:          true
auto:          true
