permalink:     /:year-:month-:day/:title
url:           http://geek-zh.tk
author:        Geek_Pig
paginate:      15
markdown:      redcarpet
pygments:      true
safe:          true
auto:          true
