name:      间歇性折腾
pygments:  true
mardown:   redcarpet
markdown_ext: markdown,mkd,mkdn,md
redcarpet: 
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
source:    .
destination: ./_site
layouts:   ./_layouts
permalink: /:year-:month-:day/:title.html 
baseurl:   /
paginate:  5
paginate_path: "page:num"

